# Generated by Django 4.2.6 on 2023-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayprompt',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roleplayprompt',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='roleplayprompt',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
