# Generated by Django 4.2.6 on 2023-11-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0002_roleplayprompt_difficulty_roleplayprompt_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplayprompt',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
