# Generated by Django 4.2.7 on 2023-11-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_alter_wordcard_deck'),
        ('roleplay', '0003_alter_roleplayprompt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordUseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnt_date', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_use_history', to='decks.wordcard')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleplay.roleplayprompt')),
            ],
        ),
    ]
