# Generated by Django 4.2.6 on 2023-10-15 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('ME', 'meanings'), ('KJ', 'kanji'), ('SY', 'synonyms'), ('AN', 'antonyms'), ('RW', 'related words'), ('GM', 'grammars')], max_length=2)),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordLearnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnt_date', models.DateField(auto_now=True)),
                ('easiness', models.IntegerField(default=1)),
                ('interval', models.IntegerField(default=1)),
                ('next_date', models.DateField(null=True)),
                ('first_visit', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.wordcard')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wordlearnhistory',
            constraint=models.UniqueConstraint(fields=('card', 'learnt_date'), name='unique_card_date_combination'),
        ),
    ]
