# Generated by Django 4.2.6 on 2023-10-20 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_worddict_definitions'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordcard',
            name='content',
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.worddict'),
        ),
    ]
