# Generated by Django 4.2.6 on 2023-10-21 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_alter_wordlearnhistory_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_card', to='decks.deck'),
        ),
    ]
