# Generated by Django 4.2.6 on 2023-10-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('en_sentence', models.CharField(max_length=1000)),
                ('jp_sentence', models.CharField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definitions', models.CharField(max_length=1000)),
                ('hiragana', models.CharField(max_length=100)),
                ('kanji', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('image', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
