# Generated by Django 4.2.6 on 2023-10-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_worddict_definitions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worddict',
            constraint=models.UniqueConstraint(fields=('word',), name='word_unique'),
        ),
    ]
