# Generated by Django 4.2.6 on 2023-11-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_worddict_word_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddict',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
